Fix error with polling
If you call `var pymChild = new pym.Child({polling: 1000});`you get the followinf error because 'this'
 is the iframes windo object instead of the pym.Child object.

    Uncaught TypeError: undefined is not a function pym.js:432
      lib.Child.sendHeight pym.js:432